### ISSUE TITLE
Model code

### ISSUE THREAD

**Issue by lml125** [RammusLeo/DPMesh#3]
Hi,bro.Why is the code of your model exactly the same as the code of JOTR's model? Did you put the wrong code?

**Comment by RammusLeo** [comment]
Hi! Thanks for your interests. We have borrowed the codebase of JOTR and we highlight our acknowledgement in the README. Our main contribution is the Diffusion backbone, which is included in the `./common/vpd` and `./cldm`. We follow the JOTR's well-designed cascade transformer regressor but we conduce ablation study to verify our improvement is brought from our Diffusion backbone, as shown in table.C, appendix.
