### ISSUE TITLE
link

### ISSUE THREAD

**Issue by lzzzbbbbb** [RammusLeo/DPMesh#4]
The links for the Human3.6M parsed data and SMPL parameters, as well as the MuCo parsed/composited data and SMPL parameters, are no longer active. Could you please provide alternative sources or updated links for these resources?

**Comment by RammusLeo** [comment]
[H36M data](https://drive.google.com/drive/folders/1r0B9I3XxIIW_jsXjYinDpL6NFcxTZart?usp=share_link)
[H36M SMPL](https://drive.google.com/drive/folders/12fCumEgs9PXT-dAaOGq0EDpl9dGKKorF?usp=share_link)
[MuCo data](https://drive.google.com/drive/folders/1dfhFa1kBHYKLTKuprNc7xixt3yyKEky5?usp=share_link)
[MuCo SMPL](https://drive.google.com/drive/folders/1Wm1_6tn1u-_RE1iUlibIWfS75O79aJRz?usp=share_link)
It looks like these links can reach to the target data repo successfully? If you cannot download the data, you can refer to the tips below: 
```
* Go the shared folder, which contains files you want to copy to your drive  
* Select all the files you want to copy  
* In the upper right corner click on three vertical dots and select “make a copy”  
* Then, the file is copied to your personal google drive account. You can download it from your personal account.  
```
